#!/bin/bash

# Gather data

# Get the current logged in user
USER=$(whoami)

# Get the current date and time in the default format
DATETIME=$(date)

# Get the system's hostname (name of the machine)
HOSTNAME=$(hostname)

# Source the /etc/os-release file to gather OS information like name and version
source /etc/os-release
OS_NAME=$NAME          # OS name (e.g., Ubuntu)
OS_VERSION=$VERSION    # OS version (e.g., 20.04 LTS)

# Get system uptime (how long the system has been running)
UPTIME=$(uptime -p)

# Get the CPU model name using lscpu command and filter the "Model name"
CPU=$(lscpu | grep "Model name" | awk -F: '{print $2}' | xargs)

# Get the total installed RAM using the free command and extract the value from the second column (RAM size)
RAM=$(free -h | grep Mem | awk '{print $2}')

# Get disk information, including the device names, sizes, and models using lsblk
DISK=$(lsblk -o NAME,SIZE,MODEL | grep -v "NAME" | xargs)

# Get the video card information using lshw and extract the product name from the output
VIDEO=$(lshw -class video | grep "product:" | awk -F: '{print $2}' | xargs)

# Get the fully qualified domain name (FQDN) of the system
FQDN=$(hostname -f)

# Get the primary IP address of the system (for the interface connected to the network)
IP_ADDRESS=$(ip a | grep inet | grep -v inet6 | awk '{print $2}' | cut -d/ -f1)

# Get the default gateway IP address using the ip route command
GATEWAY=$(ip r | grep default | awk '{print $3}')

# Get the DNS server IP address from the /etc/resolv.conf file
DNS_SERVER=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2}')

# Get a list of users currently logged into the system
USERS_LOGGED_IN=$(who | awk '{print $1}' | xargs)

# Get the available disk space on mounted filesystems and output the file system name and available space
DISK_SPACE=$(df -h | grep -v "Filesystem" | awk '{print $1 " " $4}')

# Get the process count (total number of processes running) by counting lines in the `ps aux` output
PROCESS_COUNT=$(ps aux | wc -l)

# Get the system load averages (for 1, 5, and 15 minute intervals) from the uptime command
LOAD_AVG=$(uptime | awk -F'load average:' '{print $2}' | xargs)

# Get the list of listening network ports (TCP/UDP) using ss command and extract the local address column
LISTENING_PORTS=$(ss -tuln | awk '{print $5}' | grep -v "Local" | xargs)

# Get the status of UFW (Uncomplicated Firewall) and extract the second line of the status output
UFW_STATUS=$(sudo ufw status | head -n 2 | tail -n 1 | awk '{print $2}')

# Output the report

# Output a blank line at the start to separate the report from shell prompts
echo -e "\nSystem Report generated by $USER, $DATETIME\n"

# Print the system information header
echo "System Information"
echo "------------------"
# Output the system's hostname
echo "Hostname: $HOSTNAME"
# Output the OS name and version
echo "OS: $OS_NAME $OS_VERSION"
# Output the system's uptime
echo "Uptime: $UPTIME"

# Add a blank line before starting hardware information
echo -e "\nHardware Information"
echo "--------------------"
# Output the CPU model name and model number
echo "CPU: $CPU"
# Output the amount of RAM installed on the system
echo "RAM: $RAM"
# Output disk(s) information: model and size for all installed disks
echo "Disk(s): $DISK"
# Output video card model name
echo "Video: $VIDEO"

# Add a blank line before starting network information
echo -e "\nNetwork Information"
echo "-------------------"
# Output the fully qualified domain name
echo "FQDN: $FQDN"
# Output the IP address for the interface connected to the network
echo "Host Address: $IP_ADDRESS"
# Output the default gateway IP address
echo "Gateway IP: $GATEWAY"
# Output the DNS server IP address
echo "DNS Server: $DNS_SERVER"

# Add a blank line before starting system status information
echo -e "\nSystem Status"
echo "-------------"
# Output a list of users currently logged in
echo "Users Logged In: $USERS_LOGGED_IN"
# Output the available disk space for mounted filesystems
echo "Disk Space: $DISK_SPACE"
# Output the total number of running processes
echo "Process Count: $PROCESS_COUNT"
# Output the system's load averages for the last 1, 5, and 15 minutes
echo "Load Averages: $LOAD_AVG"
# Output the list of network ports currently being listened to by the system
echo "Listening Network Ports: $LISTENING_PORTS"
# Output the status of the UFW firewall (enabled or disabled)
echo "UFW Status: $UFW_STATUS"

# Add a blank line at the end to clearly separate the report from the shell prompt
echo -e "\n"

