#!/bin/bash

# Gather data
USER=$(whoami)
DATETIME=$(date)
HOSTNAME=$(hostname)
source /etc/os-release
OS_NAME=$NAME
OS_VERSION=$VERSION
UPTIME=$(uptime -p)
CPU=$(lscpu | grep "Model name" | awk -F: '{print $2}' | xargs)
RAM=$(free -h | grep Mem | awk '{print $2}')
DISK=$(lsblk -o NAME,SIZE,MODEL | grep -v "NAME" | xargs)
VIDEO=$(lshw -class video | grep "product:" | awk -F: '{print $2}' | xargs)
FQDN=$(hostname -f)
IP_ADDRESS=$(ip a | grep inet | grep -v inet6 | awk '{print $2}' | cut -d/ -f1)
GATEWAY=$(ip r | grep default | awk '{print $3}')
DNS_SERVER=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2}')
USERS_LOGGED_IN=$(who | awk '{print $1}' | xargs)
DISK_SPACE=$(df -h | grep -v "Filesystem" | awk '{print $1 " " $4}')
PROCESS_COUNT=$(ps aux | wc -l)
LOAD_AVG=$(uptime | awk -F'load average:' '{print $2}' | xargs)
LISTENING_PORTS=$(ss -tuln | awk '{print $5}' | grep -v "Local" | xargs)
UFW_STATUS=$(sudo ufw status | head -n 2 | tail -n 1 | awk '{print $2}')

# Output the report
echo -e "\nSystem Report generated by $USER, $DATETIME\n"
echo "System Information"
echo "------------------"
echo "Hostname: $HOSTNAME"
echo "OS: $OS_NAME $OS_VERSION"
echo "Uptime: $UPTIME"
echo -e "\nHardware Information"
echo "--------------------"
echo "CPU: $CPU"
echo "RAM: $RAM"
echo "Disk(s): $DISK"
echo "Video: $VIDEO"
echo -e "\nNetwork Information"
echo "-------------------"
echo "FQDN: $FQDN"
echo "Host Address: $IP_ADDRESS"
echo "Gateway IP: $GATEWAY"
echo "DNS Server: $DNS_SERVER"
echo -e "\nSystem Status"
echo "-------------"
echo "Users Logged In: $USERS_LOGGED_IN"
echo "Disk Space: $DISK_SPACE"
echo "Process Count: $PROCESS_COUNT"
echo "Load Averages: $LOAD_AVG"
echo "Listening Network Ports: $LISTENING_PORTS"
echo "UFW Status: $UFW_STATUS"
echo -e "\n"
